#!/usr/bin/env lua

-- Get script directory and set up package path
local function get_script_dir()
	local source = (arg and arg[0]) or ""
	local path = source:match("(.+[\\/])")
	if path then
		return path:gsub("\\", "/")
	end
	return "./"
end

local script_dir = get_script_dir()
package.path = script_dir .. "?.lua;" .. script_dir .. "mappers/?.lua;" .. package.path

local utils = require("utils")

-- Configuration
local VARS_DIR = script_dir .. "vars"
local MODULES_DIR = script_dir .. "modules"
local PATHS_DIR = script_dir .. "paths"
local GENERATED_DIR = script_dir .. "generated"
local MACHINE_FILE = script_dir .. "../.machine.local.lua"

-- Load machine configuration
local machine = utils.load_file(MACHINE_FILE)
if not machine then
	print("Error: Could not load " .. MACHINE_FILE)
	os.exit(1)
end

-- Determine shell type: explicit machine.shell, else infer from os.type
local shell_type = machine.shell
if not shell_type then
	if machine.os and machine.os.type == "windows" then
		shell_type = "pwsh"
	else
		shell_type = "zsh"
	end
end

local visual_type = machine.os and machine.os.visual
local machine_os_type = machine.os and machine.os.type

print("Machine: " .. machine.name)
if machine.os then
	print("OS: " .. machine.os.type .. (machine.os.distro and (" (" .. machine.os.distro .. ")") or ""))
end
print("Shell: " .. shell_type)
print("")

-- Load all vars and paths
local vars, var_order = utils.load_all_vars(VARS_DIR)
local paths = utils.load_all_paths(PATHS_DIR)
print("Loaded vars from " .. VARS_DIR)

-- Sort vars by dependency order
var_order = utils.dependency_sort(vars, var_order, machine.name, shell_type, visual_type, machine_os_type)

local function resolve_processed_var(name)
	local var_def = vars[name]
	if not var_def then
		return nil
	end

	if not utils.should_include(var_def, machine.name, shell_type, visual_type, machine_os_type) then
		return nil
	end

	local value = utils.resolve_value(var_def, machine.name, shell_type)
	if not value then
		return nil
	end

	value = utils.expand_value(value, vars, machine.name, shell_type)
	value = utils.process_value(value, shell_type)
	return value
end

-- Determine which mapper to use based on shell type
local mapper_path = "mappers." .. shell_type .. ".profile"

local ok, mapper = pcall(require, mapper_path)
if not ok then
	print("Error: Could not load mapper: " .. mapper_path)
	print(mapper)
	os.exit(1)
end

-- Generate output
print("Generating with " .. shell_type .. " mapper...")

local success, result, module_count = mapper.generate(vars, var_order, machine, MODULES_DIR, GENERATED_DIR, paths)
if success then
	print("Generated: " .. result .. " (" .. module_count .. " modules)")
else
	print("Error: " .. result)
	os.exit(1)
end

-- Link profile to system location
if mapper.link then
	local system_ps_profile = resolve_processed_var("systemPsProfile")
	local link_ok, link_err = mapper.link(GENERATED_DIR, system_ps_profile)
	if not link_ok and link_err then
		print("Link: " .. link_err)
	end
end

-- Always generate nushell profile (cross-platform, always useful)
if shell_type ~= "nushell" then
	local ok_nu, nu_mapper = pcall(require, "mappers.nushell.profile")
	if ok_nu then
		print("Generating nushell profile...")
		local nu_ok, nu_result, nu_count = nu_mapper.generate(vars, var_order, machine, MODULES_DIR, GENERATED_DIR, paths)
		if nu_ok then
			print("Generated: " .. nu_result .. " (" .. nu_count .. " modules)")
			if nu_mapper.link then
				local link_ok, link_err = nu_mapper.link(GENERATED_DIR)
				if not link_ok and link_err then
					print("Link: " .. link_err)
				end
			end
		else
			print("Warning: nushell profile generation failed: " .. nu_result)
		end
	end
end

-- Generate profile.lua with name -> path mapping
local profile_lines = {
	"-- Auto-generated by shell/run.lua",
	"-- Machine: " .. machine.name,
	"-- Do not edit manually",
	"",
	"return {",
}

for _, name in ipairs(var_order) do
	local var_def = vars[name]
	if utils.should_include(var_def, machine.name, shell_type, visual_type, machine_os_type) then
		local value = utils.resolve_value(var_def, machine.name, shell_type)
		if value then
			value = utils.expand_value(value, vars, machine.name, shell_type)
			value = utils.process_value(value, shell_type)
			value = value:gsub('"', '\\"')
			table.insert(profile_lines, string.format('\t%s = "%s",', name, value))
		end
	end
end

table.insert(profile_lines, "}")
table.insert(profile_lines, "")

local profile_content = table.concat(profile_lines, "\n")
local profile_path = GENERATED_DIR .. "/profile.lua"

local profile_ok, profile_err = utils.write_file(profile_path, profile_content)
if profile_ok then
	print("Generated: " .. profile_path)
else
	print("Error generating profile.lua: " .. profile_err)
	os.exit(1)
end

print("")
print("Done!")
