#!/usr/bin/env lua

-- Get script directory and set up package path
local script_dir = arg[0]:match("(.*/)")
if not script_dir then
	script_dir = "./"
end
package.path = script_dir .. "?.lua;" .. script_dir .. "mappers/?.lua;" .. package.path

local utils = require("utils")

-- Configuration
local VARS_DIR = script_dir .. "vars"
local MODULES_DIR = script_dir .. "modules"
local GENERATED_DIR = script_dir .. "generated"
local MACHINE_FILE = script_dir .. "../.machine.local.lua"

-- Load machine configuration
local machine = utils.load_file(MACHINE_FILE)
if not machine then
	print("Error: Could not load " .. MACHINE_FILE)
	os.exit(1)
end

print("Machine: " .. machine.name)
print("OS: " .. machine.os.type .. (machine.os.distro and (" (" .. machine.os.distro .. ")") or ""))
print("")

-- Load all vars
local vars, var_order = utils.load_all_vars(VARS_DIR)
print("Loaded vars from " .. VARS_DIR)

-- Sort vars by dependency order
var_order = utils.dependency_sort(vars, var_order, machine.name, machine.os.type)

-- Determine which mapper to use based on OS type
local mapper_name = machine.os.type
local mapper_path = "mappers." .. mapper_name .. ".profile"

local ok, mapper = pcall(require, mapper_path)
if not ok then
	print("Error: Could not load mapper: " .. mapper_path)
	print(mapper)
	os.exit(1)
end

-- Generate output
print("Generating with " .. mapper_name .. " mapper...")

local success, result, module_count = mapper.generate(vars, var_order, machine, MODULES_DIR, GENERATED_DIR)
if success then
	print("Generated: " .. result .. " (" .. module_count .. " modules)")
else
	print("Error: " .. result)
	os.exit(1)
end

-- Link profile to system location
if mapper.link then
	local link_ok, link_err = mapper.link(GENERATED_DIR)
	if not link_ok and link_err then
		print("Link: " .. link_err)
	end
end

-- Generate profile.lua with name -> path mapping
local os_type = machine.os.type
local profile_lines = {
	"-- Auto-generated by shell/run.lua",
	"-- Machine: " .. machine.name,
	"-- Do not edit manually",
	"",
	"return {",
}

for _, name in ipairs(var_order) do
	local var_def = vars[name]
	if utils.should_include(var_def, machine.name, os_type) then
		local value = utils.resolve_value(var_def, machine.name, os_type)
		if value then
			-- Fully expand all variable references first
			value = utils.expand_value(value, vars, machine.name, os_type)
			-- Then process (normalize paths, etc.)
			value = utils.process_value(value, os_type)
			-- Escape any quotes in the value
			value = value:gsub('"', '\\"')
			table.insert(profile_lines, string.format('\t%s = "%s",', name, value))
		end
	end
end

table.insert(profile_lines, "}")
table.insert(profile_lines, "")

local profile_content = table.concat(profile_lines, "\n")
local profile_path = GENERATED_DIR .. "/profile.lua"

local profile_ok, profile_err = utils.write_file(profile_path, profile_content)
if profile_ok then
	print("Generated: " .. profile_path)
else
	print("Error generating profile.lua: " .. profile_err)
	os.exit(1)
end

print("")
print("Done!")
