# --- windows / psmux: powershell ports of popular tmux plugins ---
set -g @plugin 'psmux-plugins/ppm'

set -g @plugin 'psmux-plugins/psmux-resurrect'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'

set -g @plugin 'psmux-plugins/psmux-continuum'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

run '~/.config/tmux/plugins/ppm/ppm.ps1'
