#!/usr/bin/env lua

local function get_script_dir()
	local source = debug.getinfo(1, "S").source:gsub("^@", "")
	if source == "" and arg and arg[0] then
		source = arg[0]
	end
	local path = source:match("(.+[\\/])")
	if not path then
		return "."
	end
	path = path:gsub("\\", "/"):gsub("/$", "")
	if path:sub(1, 1) == "/" then
		return path
	end

	local handle = io.popen("pwd")
	local cwd = handle and handle:read("*l") or "."
	if handle then
		handle:close()
	end
	return (cwd:gsub("/$", "") .. "/" .. path):gsub("/%./", "/")
end

local services_dir = get_script_dir()
local dotfiles_dir = services_dir:gsub("/unix/services$", "")

package.path = dotfiles_dir .. "/shell/mappers/?.lua;" .. dotfiles_dir .. "/infra/?.lua;" .. package.path

local utils = require("utils")

local M = {}

local function quote_arg(value)
	value = tostring(value)
	if value:match("^[%w%._%+%-%/:=@]+$") then
		return value
	end
	return '"' .. value:gsub("\\", "\\\\"):gsub('"', '\\"') .. '"'
end

local function shell_quote(value)
	return "'" .. tostring(value):gsub("'", "'\\''") .. "'"
end

local function expand_env(value)
	if type(value) ~= "string" then
		return value
	end
	value = value:gsub("%${HOME}", os.getenv("HOME") or "")
	value = value:gsub("%$HOME", os.getenv("HOME") or "")
	value = value:gsub("%${([%w_]+)}", function(name)
		return os.getenv(name) or ("${" .. name .. "}")
	end)
	return value
end

local function command_path(command)
	if command:find("/", 1, true) then
		return expand_env(command)
	end

	local handle = io.popen("command -v " .. shell_quote(command) .. " 2>/dev/null")
	local resolved = handle and handle:read("*l") or nil
	if handle then
		handle:close()
	end
	if resolved and resolved ~= "" then
		return resolved
	end
	return command
end

local function read_machine()
	return utils.load_file(dotfiles_dir .. "/.machine.local.lua")
end

local function sorted_lua_files(dir)
	local files = {}
	local handle = io.popen('find "' .. dir .. '" -maxdepth 1 -name "*.lua" -type f 2>/dev/null')
	if handle then
		for file in handle:lines() do
			table.insert(files, file)
		end
		handle:close()
	end
	table.sort(files)
	return files
end

local function should_include(service, machine)
	local machine_name = machine and machine.name or nil
	local os_type = machine and machine.os and machine.os.type or nil
	local visual_type = machine and machine.os and machine.os.visual or nil
	return utils.should_include(service, machine_name, os_type, visual_type, os_type)
end

local function unit_name(service)
	return "dotfiles-" .. service.name .. ".service"
end

local function unit_content(service)
	local command = {}
	for i, part in ipairs(service.command or {}) do
		local value = expand_env(part)
		if i == 1 then
			value = command_path(value)
		end
		table.insert(command, quote_arg(value))
	end

	local lines = {
		"# Generated by dotfiles unix/services/generator.lua",
		"# Do not edit manually",
		"",
		"[Unit]",
		"Description=" .. (service.description or service.name),
		"",
		"[Service]",
		"ExecStart=" .. table.concat(command, " "),
	}

	if service.restart then
		table.insert(lines, "Restart=" .. service.restart)
	end

	table.insert(lines, "")
	table.insert(lines, "[Install]")
	table.insert(lines, "WantedBy=" .. (service.wanted_by or "default.target"))
	table.insert(lines, "")

	return table.concat(lines, "\n")
end

local function manifest_content(services)
	local lines = { "[" }
	for _, service in ipairs(services) do
		table.insert(lines, string.format(
			"  { name: %q, unit: %q, description: %q },",
			service.name,
			unit_name(service),
			service.description or service.name
		))
	end
	table.insert(lines, "]")
	table.insert(lines, "")
	return table.concat(lines, "\n")
end

local function write_file(path, content)
	local dir = path:match("(.+)/[^/]+$")
	if dir then
		os.execute("mkdir -p " .. quote_arg(dir))
	end
	local file, err = io.open(path, "w")
	if not file then
		return false, err
	end
	file:write(content)
	file:close()
	return true
end

function M.generate()
	local machine = read_machine()
	if not machine then
		return false, "Could not load " .. dotfiles_dir .. "/.machine.local.lua"
	end

	local generated_dir = services_dir .. "/generated"
	local services = {}

	for _, file in ipairs(sorted_lua_files(services_dir .. "/defs")) do
		local service, err = utils.load_file(file)
		if not service then
			return false, "Could not load service definition " .. file .. ": " .. tostring(err)
		end
		if should_include(service, machine) then
			if type(service.name) ~= "string" or service.name == "" then
				return false, "Service definition missing name: " .. file
			end
			if type(service.command) ~= "table" or #service.command == 0 then
				return false, "Service definition missing command: " .. service.name
			end
			table.insert(services, service)
		end
	end

	table.sort(services, function(a, b) return a.name < b.name end)

	for _, service in ipairs(services) do
		local ok, err = write_file(generated_dir .. "/" .. unit_name(service), unit_content(service))
		if not ok then
			return false, "Could not write unit for " .. service.name .. ": " .. tostring(err)
		end
	end

	local ok, err = write_file(generated_dir .. "/services.nuon", manifest_content(services))
	if not ok then
		return false, "Could not write service manifest: " .. tostring(err)
	end

	return true, generated_dir, services
end

if pcall(debug.getlocal, 4, 1) == false then
	local ok, result, services = M.generate()
	if not ok then
		io.stderr:write(result .. "\n")
		os.exit(1)
	end
	print("Generated services in " .. result .. " (" .. tostring(#services) .. " services)")
end

return M
