return {
  doc = {
    { ext = { 'md', 'mdx', 'rst', 'adoc', 'txt' } },
    { segment = { 'docs', 'doc', 'documentation' } },
    { basename = { 'README*', 'CHANGELOG*', 'LICENSE*', 'CONTRIBUTING*', 'AUTHORS*', 'NOTICE*' } },
  },
  test = {
    { segment = { 'test', 'tests', 'spec', 'specs', '__tests__' } },
    {
      basename = {
        '*_test.*',
        '*_spec.*',
        '*.test.*',
        '*.spec.*',
        '*Test.cs',
        '*Tests.cs',
        '*Test.java',
        '*Test.kt',
      }
    },
  },
  generated = {
    { segment = { 'dist', 'build', 'out', 'target', 'generated', '.next', 'coverage' } },
    { basename = { '*.g.*', '*.designer.*', '*.min.js', '*.min.css', '*.pb.go', '*_pb2.py' } },
  },
  config = {
    { ext = { 'json', 'toml', 'yaml', 'yml', 'ini', 'conf', 'cfg' } },
    { basename = { 'Makefile', 'Justfile', 'Dockerfile', '.gitignore', '.gitattributes', '.editorconfig', '.env*' } },
  },
  vendored = {
    { segment = { 'node_modules', 'vendor', 'third_party', '.venv', 'venv', 'site-packages' } },
  },
  lock = {
    { basename = { 'package-lock.json', '*-lock.json', '*.lock', 'Cargo.lock', 'poetry.lock' } },
  },
  code = {
    {
      ext = {
        'c',
        'h',
        'cc',
        'cpp',
        'cxx',
        'hpp',
        'hh',
        'cs',
        'java',
        'kt',
        'kts',
        'scala',
        'groovy',
        'gradle',
        'go',
        'rs',
        'py',
        'pyi',
        'rb',
        'php',
        'pl',
        'pm',
        'lua',
        'vim',
        'js',
        'jsx',
        'mjs',
        'cjs',
        'ts',
        'tsx',
        'mts',
        'cts',
        'vue',
        'svelte',
        'astro',
        'swift',
        'm',
        'mm',
        'dart',
        'zig',
        'nim',
        'cr',
        'jl',
        'r',
        'ex',
        'exs',
        'erl',
        'hrl',
        'hs',
        'ml',
        'mli',
        'fs',
        'fsx',
        'clj',
        'cljs',
        'sql',
        'sh',
        'bash',
        'zsh',
        'fish',
        'ps1',
        'psm1',
        'css',
        'scss',
        'sass',
        'less',
        'html',
        'htm',
        'xml',
      }
    },
  },
}
