return {
  'folke/which-key.nvim',
  event = 'VimEnter',
  opts = {
    delay = 50,
    plugins = {
      presets = {
        operators = false,
        motions = false,
        text_objects = false,
        windows = false,
        nav = false,
        z = false,
        g = false,
      },
    },
    filter = function(mapping)
      return mapping.desc and mapping.desc ~= ''
    end,
    icons = {
      mappings = vim.g.have_nerd_font,
      keys = vim.g.have_nerd_font and {} or {
        Up = '<Up> ',
        Down = '<Down> ',
        Left = '<Left> ',
        Right = '<Right> ',
        C = '<C-…> ',
        M = '<M-…> ',
        D = '<D-…> ',
        S = '<S-…> ',
        CR = '<CR> ',
        Esc = '<Esc> ',
        ScrollWheelDown = '<ScrollWheelDown> ',
        ScrollWheelUp = '<ScrollWheelUp> ',
        NL = '<NL> ',
        BS = '<BS> ',
        Space = '<Space> ',
        Tab = '<Tab> ',
        F1 = '<F1>',
        F2 = '<F2>',
        F3 = '<F3>',
        F4 = '<F4>',
        F5 = '<F5>',
        F6 = '<F6>',
        F7 = '<F7>',
        F8 = '<F8>',
        F9 = '<F9>',
        F10 = '<F10>',
        F11 = '<F11>',
        F12 = '<F12>',
      },
    },

    spec = {
      { 'g',   group = 'Go to' },
      { 'gf',  desc = 'Next function' },
      { 'gF',  desc = 'Prev function' },
      { 'gt',  desc = 'Next function end' },
      { 'gT',  desc = 'Prev function end' },
      { 'gp',  desc = 'Next parameter' },
      { 'gP',  desc = 'Prev parameter' },
      { 'gc',  desc = 'Next class' },
      { 'gC',  desc = 'Prev class' },
      { 'gl',  desc = 'Next call' },
      { 'gL',  desc = 'Prev call' },
      { 'gb',  desc = 'Next block' },
      { 'gB',  desc = 'Prev block' },
      { 'gi',  desc = 'Next conditional' },
      { 'gI',  desc = 'Prev conditional' },
      { 'go',  desc = 'Next loop' },
      { 'gO',  desc = 'Prev loop' },
      { 'gu',  desc = 'Next return' },
      { 'gU',  desc = 'Prev return' },
      { 'ga',  desc = 'Next assignment' },
      { 'gA',  desc = 'Prev assignment' },
      { '<leader>s',  group = '[S]earch' },
      { '<leader>t',  group = '[T]oggle' },
      { '<leader>d',  group = '[D]ebug' },
      { '<leader>h',  group = 'Git [H]unk',  mode = { 'n', 'v' } },
      { '<leader>z',  group = 'Region Folds' },
      { '<leader>n',  group = '[N]avigate' },
      { '<leader>w',  group = '[W]rite' },
      { '<leader>x',  group = 'Issues' },
      { '<leader>r',  group = 'Edit Helpers' },
      { '<leader>b',  group = '[B]uffer' },
      { '<leader>g',  group = 'Misc' },
      { '<leader>gc', group = 'Diffview' },
      { '<leader>l',  group = 'File Locals' },
      { '<leader>o',  group = 'Tests' },
    },
  },
}
