set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @sessionx-bind 'o'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g repeat-time 750

set -g extended-keys on
set -as terminal-features 'foot*:extkeys'

set-hook -g session-created 'run-shell "printf \"\\033[>1u\" > #{client_tty}"'
set-hook -g client-attached 'run-shell "printf \"\\033[>1u\" > #{client_tty}"'
