set -g status-position top
set -g status-right ''
set -g status-justify left
set -g status-style "bg=#2f3045,fg=#ffffff"

setw -g window-status-format " #I:#W "
setw -g window-status-current-format " #I:#W "
setw -g window-status-current-style "bold,fg=#ffffff,bg=#5cb2ed"
setw -g window-status-style "fg=#ffffff,bg=#111111"
setw -g window-status-separator ""
