local utils = require("utils")

local M = {}

-- Linking: profile.ps1 -> PowerShell profile
function M.link(output_dir)
	local source = output_dir .. "/profile.ps1"

	-- PowerShell profile location: $HOME\Documents\PowerShell\Microsoft.PowerShell_profile.ps1
	local home = os.getenv("USERPROFILE")
	if not home then return false, "USERPROFILE not set" end

	local target_dir = home .. "\\Documents\\PowerShell"
	local target = target_dir .. "\\Microsoft.PowerShell_profile.ps1"

	-- Create directory if needed
	os.execute('mkdir "' .. target_dir .. '" 2>nul')

	-- Check if target exists
	local f = io.open(target, "r")
	if f then
		f:close()
		-- Check if it's already a symlink to our file
		local handle = io.popen('cmd /c "fsutil reparsepoint query "' .. target .. '" 2>nul | findstr /c:"' .. source .. '"')
		if handle then
			local result = handle:read("*a")
			handle:close()
			if result and result:match(source:gsub("\\", "\\\\")) then
				print("Already linked: " .. target)
				return true
			end
		end
		return false, "Target exists: " .. target
	end

	-- Create symlink (requires admin or dev mode)
	local cmd = 'mklink "' .. target .. '" "' .. source:gsub("/", "\\") .. '"'
	local ok = os.execute('cmd /c "' .. cmd .. '"')
	if ok == 0 or ok == true then
		print("Linked: " .. target .. " -> " .. source)
		return true
	end
	return false, "Failed to create symlink (may need admin)"
end

local function get_module_files(dir, extension)
	local files = {}
	local handle = io.popen('ls -1 "' .. dir .. '"/*' .. extension .. ' 2>/dev/null')
	if not handle then return files end
	for file in handle:lines() do
		table.insert(files, file)
	end
	handle:close()
	return files
end

local function get_filename(path)
	return path:match("([^/]+)$")
end

local function get_basename(path)
	return path:match("([^/]+)$"):match("(.+)%.[^.]+$")
end

function M.generate(vars, var_order, machine, modules_dir, output_dir)
	local lines = {
		"# Auto-generated by shell/run.lua",
		"# Machine: " .. machine.name,
		"# Do not edit manually",
		"",
		"# Environment variables",
	}

	local os_type = "windows"
	local dir_functions = {}

	-- Environment variables
	for _, name in ipairs(var_order) do
		local var_def = vars[name]
		if utils.should_include(var_def, machine.name, os_type) then
			local value = utils.resolve_value(var_def, machine.name, os_type)
			if value then
				value = utils.process_value(value, os_type)
				table.insert(lines, string.format('$%s = "%s"', name, value))
				if utils.has_dir_function(var_def) then
					table.insert(dir_functions, name)
				end
			end
		end
	end

	-- Directory functions
	if #dir_functions > 0 then
		table.insert(lines, "")
		table.insert(lines, "# Directory navigation functions")
		for _, name in ipairs(dir_functions) do
			table.insert(lines, string.format([[
function %s {
  Set-Location $%s
}]], name, name))
		end
	end

	-- Modules
	local platform_dir = modules_dir .. "/windows"
	local module_files = get_module_files(platform_dir, ".ps1")
	local included_modules = {}

	for _, file in ipairs(module_files) do
		local filename = get_filename(file)
		local basename = get_basename(file)
		local meta_path = platform_dir .. "/" .. filename .. ".lua"
		local meta = utils.load_file(meta_path)

		local include = true
		if meta and meta.only then
			include = false
			for _, allowed in ipairs(meta.only) do
				if allowed == machine.name then
					include = true
					break
				end
			end
		end

		if include then
			table.insert(included_modules, { file = file, name = basename })
		end
	end

	if #included_modules > 0 then
		table.insert(lines, "")
		table.insert(lines, "# Modules")
		for _, mod in ipairs(included_modules) do
			table.insert(lines, '. "' .. mod.file .. '"')
		end
	end

	table.insert(lines, "")

	local content = table.concat(lines, "\n")
	local output_path = output_dir .. "/profile.ps1"

	local ok, err = utils.write_file(output_path, content)
	if not ok then
		return false, err
	end

	return true, output_path, #included_modules
end

return M
