local utils = require("utils")

local M = {}

local function is_windows()
	return package.config:sub(1, 1) == "\\"
end

local function quote_arg(arg)
	return '"' .. tostring(arg):gsub('"', '\\"') .. '"'
end

-- Expand remaining shell env var references (e.g. $HOME) to their actual values.
-- This is needed because nushell does not expand $VAR in plain strings at runtime.
local function expand_env_vars(value)
	return value:gsub("%$([A-Za-z_][A-Za-z0-9_]*)", function(name)
		local val = os.getenv(name) or os.getenv(name:upper())
		-- On Windows, $HOME may not be set; fall back to USERPROFILE
		if not val and name:upper() == "HOME" then
			val = os.getenv("USERPROFILE")
		end
		if val then
			return val:gsub("\\", "/")
		end
		return "$" .. name
	end)
end

local function ensure_source_line(config_path, profile_path)
	local source_line = 'source "' .. profile_path .. '"'

	local f = io.open(config_path, "r")
	if not f then
		f = io.open(config_path, "w")
		if not f then
			return false, "Could not create " .. config_path
		end
		f:write("# Dotfiles profile\n" .. source_line .. "\n")
		f:close()
		print("Created nushell config with source line")
		return true
	end

	local content = f:read("*a")
	f:close()

	if content:find(profile_path, 1, true) then
		print("Nushell config already sources profile")
		return true
	end

	f = io.open(config_path, "a")
	if not f then
		return false, "Could not write to " .. config_path
	end
	f:write("\n# Dotfiles profile\n" .. source_line .. "\n")
	f:close()

	print("Added source line to nushell config")
	return true
end

function M.link(output_dir)
	local abs_dir
	if is_windows() then
		local handle = io.popen("cd")
		local cwd = handle and handle:read("*l") or ""
		if handle then handle:close() end
		cwd = cwd:gsub("\r", ""):gsub("\\", "/")
		abs_dir = cwd .. "/" .. output_dir:gsub("^[./\\]+", "")
	else
		local handle = io.popen('cd ' .. quote_arg(output_dir) .. ' && pwd')
		abs_dir = handle and handle:read("*l") or output_dir
		if handle then handle:close() end
	end

	local profile = abs_dir .. "/profile.nu"

	-- On Windows nushell uses %APPDATA%\nushell\, on Unix ~/.config/nushell/
	local config_dir
	if is_windows() then
		local appdata = (os.getenv("APPDATA") or ""):gsub("\\", "/")
		if appdata == "" then
			return false, "APPDATA not set"
		end
		config_dir = appdata .. "/nushell"
		os.execute('cmd /c if not exist ' .. quote_arg(config_dir:gsub("/", "\\")) ..
			' mkdir ' .. quote_arg(config_dir:gsub("/", "\\")))
	else
		local home = os.getenv("HOME")
		if not home then
			return false, "HOME not set"
		end
		config_dir = home .. "/.config/nushell"
		os.execute('mkdir -p ' .. quote_arg(config_dir))
	end

	ensure_source_line(config_dir .. "/config.nu", profile)
	return true
end

local function get_module_files(dir, extension)
	local files = {}
	local handle
	if is_windows() then
		local function quote_cmd_arg(arg)
			return '"' .. tostring(arg):gsub('"', '\\"') .. '"'
		end
		handle = io.popen('cmd /c dir /b /a-d ' ..
			quote_cmd_arg(dir:gsub("/", "\\") .. "\\*" .. extension) .. " 2>nul")
		if not handle then return files end
		for file in handle:lines() do
			local clean = file:gsub("\r", "")
			table.insert(files, dir .. "/" .. clean)
		end
	else
		handle = io.popen('ls -1 ' .. quote_arg(dir) .. '/*' .. extension .. " 2>/dev/null")
		if not handle then return files end
		for file in handle:lines() do
			table.insert(files, file)
		end
	end
	handle:close()
	return files
end

local function get_filename(path)
	return path:match("([^/]+)$")
end

local function get_basename(path)
	return path:match("([^/]+)$"):match("(.+)%.[^.]+$")
end

function M.generate(vars, var_order, machine, modules_dir, output_dir)
	local abs_modules_dir
	if is_windows() then
		if modules_dir:match("^%a:") then
			-- Already absolute
			abs_modules_dir = modules_dir:gsub("\\", "/")
		else
			-- Relative: combine with CWD
			local h = io.popen("cd")
			local cwd = h and h:read("*l") or ""
			if h then h:close() end
			cwd = cwd:gsub("\r", ""):gsub("\\", "/")
			abs_modules_dir = cwd .. "/" .. modules_dir:gsub("^[./\\]+", ""):gsub("\\", "/")
		end
	else
		local handle = io.popen('cd ' .. quote_arg(modules_dir) .. ' && pwd')
		abs_modules_dir = handle and handle:read("*l") or modules_dir
		if handle then handle:close() end
	end

	local lines = {
		"# Auto-generated by shell/run.lua",
		"# Machine: " .. machine.name,
		"# Do not edit manually",
		"",
		"# Environment variables",
	}

	local shell_type = "nushell"
	local visual_type = machine.os and machine.os.visual
	local dir_functions = {}

	-- Nushell profile uses fully-expanded literal values so variable order doesn't
	-- matter at runtime. We still iterate in dependency order for consistency.
	for _, name in ipairs(var_order) do
		local var_def = vars[name]
		if utils.should_include(var_def, machine.name, shell_type, visual_type) then
			local value = utils.resolve_value(var_def, machine.name, shell_type)
			if value then
				-- Fully expand dotfiles variable references
				value = utils.expand_value(value, vars, machine.name, shell_type)
				-- Expand remaining shell env vars (e.g. $HOME) to literal paths
				value = expand_env_vars(value)
				-- Normalize to forward slashes
				value = utils.normalize_path(value, shell_type)
				value = value:gsub('"', '\\"')
				table.insert(lines, string.format('$env.%s = "%s"', name, value))
				if utils.has_dir_function(var_def) then
					table.insert(dir_functions, name)
				end
			end
		end
	end

	if #dir_functions > 0 then
		table.insert(lines, "")
		table.insert(lines, "# Directory navigation functions")
		for _, name in ipairs(dir_functions) do
			table.insert(lines, string.format("def %s [] {\n  cd $env.%s\n}", name, name))
		end
	end

	local platform_dir = abs_modules_dir .. "/nushell"
	local module_files = get_module_files(platform_dir, ".nu")
	local included_modules = {}

	for _, file in ipairs(module_files) do
		local filename = get_filename(file)
		local basename = get_basename(file)
		local meta_path = platform_dir .. "/" .. filename .. ".lua"
		local meta = utils.load_file(meta_path)

		local include = true
		if meta then
			include = utils.should_include(meta, machine.name, shell_type, visual_type)
		end

		if include then
			table.insert(included_modules, { file = file, name = basename })
		end
	end

	if #included_modules > 0 then
		table.insert(lines, "")
		table.insert(lines, "# Modules")
		for _, mod in ipairs(included_modules) do
			table.insert(lines, 'source "' .. mod.file .. '"')
		end
	end

	table.insert(lines, "")

	local content = table.concat(lines, "\n")
	local output_path = output_dir .. "/profile.nu"

	local ok, err = utils.write_file(output_path, content)
	if not ok then
		return false, err
	end

	return true, output_path, #included_modules
end

return M
