source = ./wsl-env.conf
source = ./monitor-wsl.conf
source = ./autostart-wsl.conf

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}
