local utils = require("utils")

local M = {}

local function quote_cmd_arg(arg)
	return '"' .. tostring(arg):gsub('"', '\\"') .. '"'
end

local function get_cwd()
	local handle = io.popen("cd")
	if not handle then
		return nil
	end
	local cwd = handle:read("*l")
	handle:close()
	return cwd
end

local function to_absolute_path(path)
	if path:match("^%a:[/\\]") or path:match("^\\\\") then
		return path
	end

	local cwd = get_cwd()
	if not cwd or cwd == "" then
		return path
	end

	local clean = path:gsub("^%.[/\\]", "")
	return (cwd:gsub("\\", "/") .. "/" .. clean)
end

local function path_exists(path)
	local handle = io.popen("cmd /c if exist " .. quote_cmd_arg(path) .. " (echo yes) else (echo no)")
	if not handle then
		return false
	end
	local result = handle:read("*l")
	handle:close()
	return result == "yes"
end

local function read_reparse_info(path)
	local handle = io.popen("cmd /c fsutil reparsepoint query " .. quote_cmd_arg(path) .. " 2>nul")
	if not handle then
		return nil
	end
	local result = handle:read("*a")
	handle:close()
	if result and result ~= "" then
		return result
	end
	return nil
end

local function write_profile_shim(target, source_win)
	local f = io.open(target, "w")
	if not f then
		return false
	end
	f:write('. "' .. source_win .. '"\n')
	f:close()
	return true
end

-- Linking: profile.ps1 -> PowerShell profile
function M.link(output_dir, target_profile)
	local source = to_absolute_path(output_dir .. "/profile.ps1")
	local source_win = source:gsub("/", "\\")

	local target = target_profile and target_profile:gsub("/", "\\") or nil
	if not target or target == "" then
		return false, "systemPsProfile is not configured"
	end

	local target_dir = target:match("^(.*)\\[^\\]+$")
	if not target_dir or target_dir == "" then
		return false, "Invalid systemPsProfile path: " .. target
	end

	os.execute("cmd /c if not exist " .. quote_cmd_arg(target_dir) .. " mkdir " .. quote_cmd_arg(target_dir))

	local reparse_info = read_reparse_info(target)
	if reparse_info then
		if reparse_info:lower():find(source_win:lower(), 1, true) then
			print("Already linked: " .. target)
			return true
		end
		os.execute("cmd /c del " .. quote_cmd_arg(target) .. " 2>nul")
	end

	if path_exists(target) then
		return false, "Target exists: " .. target
	end

	local cmd = 'mklink "' .. target .. '" "' .. source_win .. '"'
	local ok = os.execute('cmd /c "' .. cmd .. '"')
	if ok == 0 or ok == true then
		print("Linked: " .. target .. " -> " .. source)
		return true
	end

	if write_profile_shim(target, source_win) then
		print("Linked (shim): " .. target .. " -> " .. source)
		return true
	end

	return false, "Failed to create symlink (may need admin)"
end

local function get_module_files(dir, extension)
	local files = {}
	local cmd = 'cmd /c dir /b /a-d ' .. quote_cmd_arg((dir:gsub("/", "\\")) .. "\\*" .. extension) .. " 2>nul"
	local handle = io.popen(cmd)
	if not handle then return files end
	for file in handle:lines() do
		local full = (dir .. "/" .. file):gsub("\\", "/")
		table.insert(files, full)
	end
	handle:close()
	return files
end

local function get_filename(path)
	return path:match("([^/]+)$")
end

local function get_basename(path)
	return path:match("([^/]+)$"):match("(.+)%.[^.]+$")
end

function M.generate(vars, var_order, machine, modules_dir, output_dir)
	local lines = {
		"# Auto-generated by shell/run.lua",
		"# Machine: " .. machine.name,
		"# Do not edit manually",
		"",
		"# Environment variables",
	}

	local shell_type = "pwsh"
	local visual_type = machine.os and machine.os.visual
	local dir_functions = {}

	for _, name in ipairs(var_order) do
		local var_def = vars[name]
		if utils.should_include(var_def, machine.name, shell_type, visual_type) then
			local value = utils.resolve_value(var_def, machine.name, shell_type)
			if value then
				value = utils.process_value(value, shell_type)
				table.insert(lines, string.format('$%s = "%s"', name, value))
				if utils.has_dir_function(var_def) then
					table.insert(dir_functions, name)
				end
			end
		end
	end

	if #dir_functions > 0 then
		table.insert(lines, "")
		table.insert(lines, "# Directory navigation functions")
		for _, name in ipairs(dir_functions) do
			table.insert(lines, string.format([[
function %s {
  Set-Location $%s
}]], name, name))
		end
	end

	local platform_dir = modules_dir .. "/pwsh"
	local module_files = get_module_files(platform_dir, ".ps1")
	local included_modules = {}

	for _, file in ipairs(module_files) do
		local filename = get_filename(file)
		local basename = get_basename(file)
		local meta_path = platform_dir .. "/" .. filename .. ".lua"
		local meta = utils.load_file(meta_path)

		local include = true
		if meta then
			include = utils.should_include(meta, machine.name, shell_type, visual_type)
		end

		if include then
			table.insert(included_modules, { filename = filename, name = basename })
		end
	end

	if #included_modules > 0 then
		table.insert(lines, "")
		table.insert(lines, "# Modules")
		for _, mod in ipairs(included_modules) do
			table.insert(lines, '. "$shellConfig/modules/pwsh/' .. mod.filename .. '"')
		end
	end

	table.insert(lines, "")

	local content = table.concat(lines, "\n")
	local output_path = output_dir .. "/profile.ps1"

	local ok, err = utils.write_file(output_path, content)
	if not ok then
		return false, err
	end

	return true, output_path, #included_modules
end

return M
