local utils = require("utils")

local M = {}

-- Ensure ~/.bashrc sources our profile.sh
function M.link(output_dir)
	-- Get absolute path
	local handle = io.popen('cd "' .. output_dir .. '" && pwd')
	local abs_dir = handle and handle:read("*l") or output_dir
	if handle then handle:close() end

	local profile = abs_dir .. "/profile.sh"
	local home = os.getenv("HOME")
	if not home then return false, "HOME not set" end

	local bashrc = home .. "/.bashrc"
	local source_line = '. "' .. profile .. '"'

	-- Read current bashrc
	local f = io.open(bashrc, "r")
	if not f then return false, "~/.bashrc not found" end
	local content = f:read("*a")
	f:close()

	-- Check if already sourcing our profile
	if content:find(profile, 1, true) then
		print("~/.bashrc already sources profile")
		return true
	end

	-- Append source line
	f = io.open(bashrc, "a")
	if not f then return false, "Could not write to ~/.bashrc" end
	f:write("\n# Dotfiles profile\n" .. source_line .. "\n")
	f:close()

	print("Added source line to ~/.bashrc")
	return true
end

local function get_module_files(dir, extension)
	local files = {}
	local handle = io.popen('ls -1 "' .. dir .. '"/*' .. extension .. ' 2>/dev/null')
	if not handle then return files end
	for file in handle:lines() do
		table.insert(files, file)
	end
	handle:close()
	return files
end

local function get_filename(path)
	return path:match("([^/]+)$")
end

local function get_basename(path)
	return path:match("([^/]+)$"):match("(.+)%.[^.]+$")
end

function M.generate(vars, var_order, machine, modules_dir, output_dir)
	local lines = {
		"# Auto-generated by shell/run.lua",
		"# Machine: " .. machine.name,
		"# Do not edit manually",
		"",
		"# Environment variables",
	}

	local os_type = "unix"
	local dir_functions = {}

	-- Environment variables
	for _, name in ipairs(var_order) do
		local var_def = vars[name]
		if utils.should_include(var_def, machine.name, os_type) then
			local value = utils.resolve_value(var_def, machine.name, os_type)
			if value then
				value = utils.process_value(value, os_type)
				table.insert(lines, string.format('export %s="%s"', name, value))
				if utils.has_dir_function(var_def) then
					table.insert(dir_functions, name)
				end
			end
		end
	end

	-- Directory functions
	if #dir_functions > 0 then
		table.insert(lines, "")
		table.insert(lines, "# Directory navigation functions")
		for _, name in ipairs(dir_functions) do
			table.insert(lines, string.format([[
%s() {
  cd "$%s"
}]], name, name))
		end
	end

	-- Modules
	local platform_dir = modules_dir .. "/unix"
	local module_files = get_module_files(platform_dir, ".sh")
	local included_modules = {}

	for _, file in ipairs(module_files) do
		local filename = get_filename(file)
		local basename = get_basename(file)
		local meta_path = platform_dir .. "/" .. filename .. ".lua"
		local meta = utils.load_file(meta_path)

		local include = true
		if meta and meta.only then
			include = false
			for _, allowed in ipairs(meta.only) do
				if allowed == machine.name then
					include = true
					break
				end
			end
		end

		if include then
			table.insert(included_modules, { file = file, name = basename })
		end
	end

	if #included_modules > 0 then
		table.insert(lines, "")
		table.insert(lines, "# Modules")
		for _, mod in ipairs(included_modules) do
			table.insert(lines, 'source "' .. mod.file .. '"')
		end
	end

	table.insert(lines, "")

	local content = table.concat(lines, "\n")
	local output_path = output_dir .. "/profile.sh"

	local ok, err = utils.write_file(output_path, content)
	if not ok then
		return false, err
	end

	return true, output_path, #included_modules
end

return M
