set -g status-position top
set -g status-right ''

set -g prefix C-a

set -g base-index 1

# Show windows centered or left
set -g status-justify left

# Style inactive vs active window
setw -g window-status-format " #I:#W "
setw -g window-status-current-format " #I:#W "
setw -g window-status-current-style "bold,fg=#ffffff,bg=#5cb2ed"
setw -g window-status-style "fg=#ffffff,bg=#111111"
set -g status-style "bg=#2f3045,fg=#ffffff"
setw -g window-status-separator ""

# #00035f
# #f75051

bind-key -n C-S-h previous-window
bind-key -n C-S-l next-window
bind-key -n C-S-t new-window
bind-key -n C-S-w kill-window
bind-key -n C-S-r command-prompt "rename-window '%%'"

# Separator style (optional powerline-ish look)
setw -g window-status-separator ""
