local utils = require("utils")

local M = {}

local function quote_arg(arg)
	return '"' .. tostring(arg):gsub('"', '\\"') .. '"'
end

local function ensure_source_line(rc_path, profile_path, rc_name)
	local source_line = '. "' .. profile_path .. '"'

	local f = io.open(rc_path, "r")
	if not f then
		f = io.open(rc_path, "w")
		if not f then
			return false, "Could not create " .. rc_name
		end
		f:write("# Dotfiles profile\n" .. source_line .. "\n")
		f:close()
		print("Created " .. rc_name .. " with source line")
		return true
	end

	local content = f:read("*a")
	f:close()

	if content:find(profile_path, 1, true) then
		print(rc_name .. " already sources profile")
		return true
	end

	f = io.open(rc_path, "a")
	if not f then
		return false, "Could not write to " .. rc_name
	end
	f:write("\n# Dotfiles profile\n" .. source_line .. "\n")
	f:close()

	print("Added source line to " .. rc_name)
	return true
end

function M.link(output_dir)
	local handle = io.popen('cd ' .. quote_arg(output_dir) .. ' && pwd')
	local abs_dir = handle and handle:read("*l") or output_dir
	if handle then handle:close() end

	local profile = abs_dir .. "/profile.bash"
	local home = os.getenv("HOME")
	if not home then
		return false, "HOME not set"
	end

	ensure_source_line(home .. "/.bashrc", profile, "~/.bashrc")

	return true
end

local function get_module_files(dir, extension)
	local files = {}
	local handle = io.popen('ls -1 ' .. quote_arg(dir) .. '/*' .. extension .. " 2>/dev/null")
	if not handle then
		return files
	end
	for file in handle:lines() do
		table.insert(files, file)
	end
	handle:close()
	return files
end

local function get_filename(path)
	return path:match("([^/]+)$")
end

local function get_basename(path)
	return path:match("([^/]+)$"):match("(.+)%.[^.]+$")
end

function M.generate(vars, var_order, machine, modules_dir, output_dir)
	local handle = io.popen('cd ' .. quote_arg(modules_dir) .. ' && pwd')
	local abs_modules_dir = handle and handle:read("*l") or modules_dir
	if handle then handle:close() end

	local lines = {
		"# Auto-generated by shell/run.lua",
		"# Machine: " .. machine.name,
		"# Do not edit manually",
		"",
		"# Environment variables",
	}

	local shell_type = "bash"
	local visual_type = machine.os and machine.os.visual
	local dir_functions = {}

	for _, name in ipairs(var_order) do
		local var_def = vars[name]
		if utils.should_include(var_def, machine.name, shell_type, visual_type) then
			local value = utils.resolve_value(var_def, machine.name, shell_type)
			if value then
				value = utils.process_value(value, shell_type)
				table.insert(lines, string.format('export %s="%s"', name, value))
				if utils.has_dir_function(var_def) then
					table.insert(dir_functions, name)
				end
			end
		end
	end

	if #dir_functions > 0 then
		table.insert(lines, "")
		table.insert(lines, "# Directory navigation functions")
		for _, name in ipairs(dir_functions) do
			table.insert(
				lines,
				string.format(
					[[
%s() {
  cd "$%s"
}]],
					name,
					name
				)
			)
		end
	end

	local platform_dir = abs_modules_dir .. "/bash"
	local module_files = get_module_files(platform_dir, ".bash")
	local included_modules = {}

	for _, file in ipairs(module_files) do
		local filename = get_filename(file)
		local basename = get_basename(file)
		local meta_path = platform_dir .. "/" .. filename .. ".lua"
		local meta = utils.load_file(meta_path)

		local include = true
		if meta then
			include = utils.should_include(meta, machine.name, shell_type, visual_type)
		end

		if include then
			table.insert(included_modules, { file = file, name = basename })
		end
	end

	if #included_modules > 0 then
		table.insert(lines, "")
		table.insert(lines, "# Modules")
		for _, mod in ipairs(included_modules) do
			table.insert(lines, 'source "' .. mod.file .. '"')
		end
	end

	table.insert(lines, "")

	local content = table.concat(lines, "\n")
	local output_path = output_dir .. "/profile.bash"

	local ok, err = utils.write_file(output_path, content)
	if not ok then
		return false, err
	end

	return true, output_path, #included_modules
end

return M
